MODEL_NAME_TRANSCRIPT = "gpt-3.5-turbo-16k"
MAX_TOKENS_TRANSCRIPT = 1000
MAX_TOKENS_ALLOWED = 16000

MODEL_NAME_QA = "gpt-3.5-turbo"
MAX_TOKENS_QA = 1000
MAX_TOKENS_QA = 4089

# BUCKET_NAME = "testasha12"

BUCKET_NAME = "ytmate-transcript-bucket"

LOCAL_DOWNLOAD_FOLDER = "downloads"
LOCAL_MODEL_FOLDER = "models"

DISABLE_IMAGE_CAPTIONING = True
